<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tedd.HashSetExtensions\Tedd.HashSetExtensions.csproj" />
    <ProjectReference Include="..\Tedd.HashSetExtensions.Archive\Tedd.HashSetExtensions.Archive.csproj" />
  </ItemGroup>
</Project>
