# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      version: '10.0.x'
      includePreviewVersions: true

  - task: UseDotNet@2
    inputs:
      version: '8.0.x'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore' # Options: build, push, pack, publish, restore, run, test, custom
      publishTestResults: true # Optional
      feedsToUse: 'select' # Options: select, config
      includeNuGetOrg: true # Required when feedsToUse == Select
      workingDirectory: src
  
  # .NET Core
  # Build, test, package, or publish a dotnet application, or run a custom dotnet command
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build' # Options: build, push, pack, publish, restore, run, test, custom
      publishTestResults: true # Optional
      feedsToUse: 'select' # Options: select, config
      includeNuGetOrg: true # Required when feedsToUse == Select
      workingDirectory: src

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test' # Options: build, push, pack, publish, restore, run, test, custom
      publishTestResults: true # Optional
      feedsToUse: 'select' # Options: select, config
      includeNuGetOrg: true # Required when feedsToUse == Select
      workingDirectory: src
