# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 8.0 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - task: UseDotNet@2
    displayName: 'Use .NET 10.0 SDK'
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
      includePreviewVersions: true

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'src/*.sln'
      publishTestResults: true
      feedsToUse: 'select'
      includeNuGetOrg: true
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'src/*.sln'
      publishTestResults: true
      feedsToUse: 'select'
      includeNuGetOrg: true

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'src/**/*Tests.csproj'
      publishTestResults: true
      feedsToUse: 'select'
      includeNuGetOrg: true
